### ISSUE TITLE
Failed to find some product

### ISSUE THREAD

**Issue by eiffel31** [yaqwsx/jlcparts#51] opened 2022-02-15 23:34 UTC
How to reproduce:
Select capacitors category (All)
search for text "220nF"
Then select qty 100
Sort by increasing price
=> unable to find C696915

Replace search text by "C696915"
=> The component is there, displayed with 220nF value (without space in the description)

**Comment by yaqwsx** [comment] 2022-03-22 07:55
This is a duplicate of #53. The reason why you don't find C696915 is that you haven't scrolled deep enough - it is there. It is just displayed at the end of the list. However, due to some components not having a price set, the sorting is broken. This is fixed in 931693a3098fa0c0692a5d8b0ef69f6f845f7fd8.

**Closed by yaqwsx** 2022-03-22 07:55 UTC
